### ISSUE TITLE
Next.jsの構築

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/nft-marketplace#1]
### 目的

NFTマーケットプレイスを開発するための環境を構築する。

#### 開発期間

- 開始：2022年10月27日
- 終了：2022年11月2日

#### 作業内容

- [x] ローカル環境にNext.jsのインストール
- [x] インストールしたNext.jsをgithubにプッシュ

### 完了要件

- nft-marketplaceリポジトリにNext.jsが反映されていること

### 参考文献

- https://nextjs.org/docs/basic-features/typescript

### 備考

- Next.js (React)
- Typescript

**Comment by towa1215** [comment]
push完了しました。

**Comment by kmasuda1986** [comment]
確認ができました！
対応ありがとうございます！
