### ISSUE TITLE
.gitignoreの追加

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/nft-marketplace#4]
### 目的

Next.jsを正しい構成に修正を行う。

mainブランチからfeature/#4ブランチを切り、プルリクを作成してから作業を始める。

### 完了要件

- [x] `.gitignore` は何をするファイルか理解ができていること
- [x] `.gitignore` を作成すること
- [x] `.gitignore` にバージョン管理しないファイルやフォルダを記載すること
- [x] `.next` ディレクトリが削除されていること
- [x] `firstproject` ディレクトリが削除されていること
- [x] `nft-marketplace` ディレクトリが削除されていること
- [x] `node_module` ディレクトリが削除されていること
- [x] `.DS_Store` ファイルが削除されていること

### ディレクトリ構成

```bash
# 変更前
nft-marketplace
 ├ .next # 削除対象
 ├ firstproject # 削除対象
 ├ my-app
 ├ nft-marketplace # 削除対象
 ├ node_module # 削除対象
 ├ .DS_Store # 削除対象
 └ README.md

# 変更後
nft-marketplace
 ├ my-app
 ├ .gitignore
 └ README.md
```

### .gitignoreに記述する内容

```
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
```

**Comment by kmasuda1986** [comment]
@towa1215 
変更前と変更後のディレクトリ構成を追加しました！

**Comment by towa1215** [comment]
全タスク完了しました。
