### ISSUE TITLE
package.jsonの初期設定

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/nft-marketplace#6]
### 目的

package.jsonの初期設定を行い、開発ができる環境を構築する。

### 完了要件

- [x] `package.json` の使用用途を理解する
- [x] `dependencies` と `devDependencies` の違いを理解する

### package.jsonの中身

```json
{
  "name": "nft_marketplace",
  "version": "1.0.0",
  "repository": "git@github.com:RuckPlus/nft-marketplace.git",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
  },
  "dependencies": {
    "next": "12.2.5",
    "next-pwa": "^5.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "typescript": "4.8.2"
  }
}
```

**Comment by towa1215** [comment]
自分なりにpackege.jsonを学びました。

# packege.jsonとは

依存関係を示したファイルで、このファイルにプロジェクトに必要なパッケージの名前とバージョンを記述すればnpmが必要なパッケージをインストールする。

packege.jsonはnode環境のアプリの設定が書かれたファイルみたいなもので、Bundlerのようなもので、開発に使う依存ライブラリと本番で使う依存ライブラリを書くことができる。

# ****dependenciesとdevDependenciesの違い****

## dependencies（アプリの実行時に必要なパッケージ）

本番環境でも利用するパッケージやその依存関係

## ****devDependencies（アプリの開発時に必要なパッケージ）****

テスト環境と開発環境で利用するパッケージやその依存関係。本番用にビルドするときは含まれない。

開発者がnpm installを行うと、dependenciesでもdevDependenciesでもすべてnode_moduleにインストールされる。しかし、開発者以外の人がnpm installするとdependenciesに書かれているパッケージのみインストールされ、devDependenciesに書かれているパッケージはインストールされない。

**Comment by kmasuda1986** [comment]
@towa1215 
こちらも完了していることを確認しました。
